[2025-07-28T12:38:30.590+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_pipeline.dbt_debug scheduled__2025-07-27T00:00:00+00:00 [queued]>
[2025-07-28T12:38:30.594+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_pipeline.dbt_debug scheduled__2025-07-27T00:00:00+00:00 [queued]>
[2025-07-28T12:38:30.594+0000] {taskinstance.py:2170} INFO - Starting attempt 15 of 16
[2025-07-28T12:38:30.598+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_debug> on 2025-07-27 00:00:00+00:00
[2025-07-28T12:38:30.600+0000] {standard_task_runner.py:60} INFO - Started process 93 to run task
[2025-07-28T12:38:30.602+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dbt_pipeline', 'dbt_debug', 'scheduled__2025-07-27T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dbt_pipeline.py', '--cfg-path', '/tmp/tmpswvt24oo']
[2025-07-28T12:38:30.603+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask dbt_debug
[2025-07-28T12:38:30.610+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-07-28T12:38:30.633+0000] {task_command.py:423} INFO - Running <TaskInstance: dbt_pipeline.dbt_debug scheduled__2025-07-27T00:00:00+00:00 [running]> on host 26b399183f28
[2025-07-28T12:38:30.670+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gotphoto' AIRFLOW_CTX_DAG_ID='dbt_pipeline' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2025-07-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='15' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-27T00:00:00+00:00'
[2025-07-28T12:38:30.671+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-28T12:38:30.671+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt_project && dbt debug --project-dir . --profiles-dir profiles']
[2025-07-28T12:38:30.676+0000] {subprocess.py:86} INFO - Output:
[2025-07-28T12:38:31.514+0000] {subprocess.py:93} INFO - [0m12:38:31  Running with dbt=1.8.7
[2025-07-28T12:38:31.520+0000] {subprocess.py:93} INFO - [0m12:38:31  dbt version: 1.8.7
[2025-07-28T12:38:31.520+0000] {subprocess.py:93} INFO - [0m12:38:31  python version: 3.8.18
[2025-07-28T12:38:31.520+0000] {subprocess.py:93} INFO - [0m12:38:31  python path: /usr/local/bin/python
[2025-07-28T12:38:31.520+0000] {subprocess.py:93} INFO - [0m12:38:31  os info: Linux-6.12.5-linuxkit-aarch64-with-glibc2.34
[2025-07-28T12:38:32.454+0000] {subprocess.py:93} INFO - [0m12:38:32  Using profiles dir at profiles
[2025-07-28T12:38:32.454+0000] {subprocess.py:93} INFO - [0m12:38:32  Using profiles.yml file at profiles/profiles.yml
[2025-07-28T12:38:32.454+0000] {subprocess.py:93} INFO - [0m12:38:32  Using dbt_project.yml file at ./dbt_project.yml
[2025-07-28T12:38:32.455+0000] {subprocess.py:93} INFO - [0m12:38:32  adapter type: snowflake
[2025-07-28T12:38:32.455+0000] {subprocess.py:93} INFO - [0m12:38:32  adapter version: 1.8.4
[2025-07-28T12:38:32.499+0000] {subprocess.py:93} INFO - [0m12:38:32  Configuration:
[2025-07-28T12:38:32.499+0000] {subprocess.py:93} INFO - [0m12:38:32    profiles.yml file [[32mOK found and valid[0m]
[2025-07-28T12:38:32.499+0000] {subprocess.py:93} INFO - [0m12:38:32    dbt_project.yml file [[32mOK found and valid[0m]
[2025-07-28T12:38:32.500+0000] {subprocess.py:93} INFO - [0m12:38:32  Required dependencies:
[2025-07-28T12:38:32.505+0000] {subprocess.py:93} INFO - [0m12:38:32   - git [[32mOK found[0m]
[2025-07-28T12:38:32.506+0000] {subprocess.py:93} INFO - 
[2025-07-28T12:38:32.506+0000] {subprocess.py:93} INFO - [0m12:38:32  Connection:
[2025-07-28T12:38:32.506+0000] {subprocess.py:93} INFO - [0m12:38:32    account: ANBZLMX-TB05856
[2025-07-28T12:38:32.506+0000] {subprocess.py:93} INFO - [0m12:38:32    user: gotphoto_etl_user
[2025-07-28T12:38:32.507+0000] {subprocess.py:93} INFO - [0m12:38:32    database: GOTPHOTO_ANALYTICS_DB
[2025-07-28T12:38:32.507+0000] {subprocess.py:93} INFO - [0m12:38:32    warehouse: GOTPHOTO_WH
[2025-07-28T12:38:32.507+0000] {subprocess.py:93} INFO - [0m12:38:32    role: gotphoto_etl_role
[2025-07-28T12:38:32.508+0000] {subprocess.py:93} INFO - [0m12:38:32    schema: STAGING
[2025-07-28T12:38:32.508+0000] {subprocess.py:93} INFO - [0m12:38:32    authenticator: None
[2025-07-28T12:38:32.508+0000] {subprocess.py:93} INFO - [0m12:38:32    oauth_client_id: None
[2025-07-28T12:38:32.509+0000] {subprocess.py:93} INFO - [0m12:38:32    query_tag: None
[2025-07-28T12:38:32.509+0000] {subprocess.py:93} INFO - [0m12:38:32    client_session_keep_alive: True
[2025-07-28T12:38:32.509+0000] {subprocess.py:93} INFO - [0m12:38:32    host: None
[2025-07-28T12:38:32.510+0000] {subprocess.py:93} INFO - [0m12:38:32    port: None
[2025-07-28T12:38:32.510+0000] {subprocess.py:93} INFO - [0m12:38:32    proxy_host: None
[2025-07-28T12:38:32.510+0000] {subprocess.py:93} INFO - [0m12:38:32    proxy_port: None
[2025-07-28T12:38:32.511+0000] {subprocess.py:93} INFO - [0m12:38:32    protocol: None
[2025-07-28T12:38:32.511+0000] {subprocess.py:93} INFO - [0m12:38:32    connect_retries: 1
[2025-07-28T12:38:32.511+0000] {subprocess.py:93} INFO - [0m12:38:32    connect_timeout: None
[2025-07-28T12:38:32.512+0000] {subprocess.py:93} INFO - [0m12:38:32    retry_on_database_errors: False
[2025-07-28T12:38:32.512+0000] {subprocess.py:93} INFO - [0m12:38:32    retry_all: False
[2025-07-28T12:38:32.512+0000] {subprocess.py:93} INFO - [0m12:38:32    insecure_mode: False
[2025-07-28T12:38:32.512+0000] {subprocess.py:93} INFO - [0m12:38:32    reuse_connections: None
[2025-07-28T12:38:32.513+0000] {subprocess.py:93} INFO - [0m12:38:32  Registered adapter: snowflake=1.8.4
[2025-07-28T12:38:33.836+0000] {subprocess.py:93} INFO - [0m12:38:33    Connection test: [[32mOK connection ok[0m]
[2025-07-28T12:38:33.837+0000] {subprocess.py:93} INFO - 
[2025-07-28T12:38:33.837+0000] {subprocess.py:93} INFO - [0m12:38:33  [32mAll checks passed![0m
[2025-07-28T12:38:34.580+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-28T12:38:34.595+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dbt_pipeline, task_id=dbt_debug, execution_date=20250727T000000, start_date=20250728T123830, end_date=20250728T123834
[2025-07-28T12:38:34.629+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-28T12:38:34.641+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
